### ISSUE TITLE
Detect color by double click

### ISSUE THREAD

**Issue by miladghiravani** [anseki/vscode-color#11]
- Extension Version:
- VS Code Version: 1.5.3
- OS Version: Windows 8.1 64-bit
- Node.js Version (result of command `node -v`): v6.5.0
- NPM Version (result of command `npm -v`): 3.10.3

Steps to Reproduce:

is better when double click then show palette color instead of `ctrl+c p`
Example:
![7bd81b62-84a8-11e6-805d-bd1aa510a044](https://cloud.githubusercontent.com/assets/5067331/18868877/a77b9d44-84b6-11e6-8bc1-022097a141ff.gif)

**Comment by anseki** [comment]
Hi @miladghiravani, thank you for the suggestion.

The launching extensions by double clicking is a feature that is implemented by VS Code rather than extensions. And current VS Code doesn't support it.
I think that VS Code supporting the feature is not easy because the double clicking works as "selecting word" like common editors, but I will examine it if VS Code future version supports it.

If you want, of course you can change the shortcut-keys by `keybindings.json`.
For example, the Color Picker dialog is opened by pressing <kbd>C</kbd> key only.

```
{"key": "c", "command": "extension.colorHelper.pick"}
```

**Comment by miladghiravani** [comment]
@anseki Thank you so much.
