### ISSUE TITLE
The new syntax for rgb is not supported

### ISSUE THREAD

**Issue by hooray** [anseki/vscode-color#118]
- Extension Version: latest
- VS Code Version: 1.61
- OS Version: win10
- Node.js Version (result of command `node -v`): 14.18.1
- NPM Version (result of command `npm -v`): 7.23.0

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/1574903/138549661-da856afe-648b-487e-8d03-a0909173aedc.png)

![image](https://user-images.githubusercontent.com/1574903/138549635-81baa5a3-fbe9-4678-8b28-8616d4ec9ca3.png)

Related references: https://stylelint.io/user-guide/rules/list/color-function-notation/

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```

```

**Comment by anseki** [comment]
Hi @hooray, thank you for the comment.
As you said, the new notation is not supported because the Color Picker for VS Code is old extension now. I think that the extension has already finished its part since VS Code supported internal color picker.
However, I think about the supporting it if more requests come.
Thank you for your report :smile:

**Comment by anseki** [comment]
I'll close this issue now but still welcome comment.
