### ISSUE TITLE
Enable vscode-color extension to run on VS Code on the Web

### ISSUE THREAD

**Issue by isidorn** [anseki/vscode-color#121]
:wave: I'm Isidor, a PM from the VS Code team, and we recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser.  You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web). 

We'd like to ensure vscode-color can run in the web, and we have a guide for enabling extensions for the web [here](https://code.visualstudio.com/api/extension-guides/web-extensions). As a couple of highlights:

- In VS Code for the Web, both the UI and extension host run inside the browser.
- A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
- Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
- There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

Please let us know if you have questions or feedback on enabling your extension for the web - our team would love to learn from your experiences and collaborate. Thank you!

**Comment by anseki** [comment]
Hi @isidorn, thank you for the comment.
I think that the making vscode-color run in the web is difficult because it uses external program. Also, I think that the extension has already finished its part since VS Code supported internal color picker.
Then, I think that changing the extension for the web is not needed.
Thank you for your proposal and the information! :smile:

**Comment by isidorn** [comment]
Thanks for providing more details. I do agree with you. Let's close this as no work planned.
