### ISSUE TITLE
color picker opens on a different space (desktop) on macos when in fullscreen

### ISSUE THREAD

**Issue by MuhsinFatih** [anseki/vscode-color#15]
Before latest update, I was unable to open color picker on mac. Now it is fixed, however the color picker opens on another space than the one vscode is open. I guess this has something to do with that the tool behaves as a window rather than a dialog, hence mac moves it to another space.

Steps to Reproduce:
1. Enter full screen on a mac
2. open the color picker

**Comment by anseki** [comment]
Hi @MuhsinFatih, thank you for the report.

The dialog box is shown in the primary display (desktop) always, because VS Code doesn't support API to access the window. That is, the extension has no way to know which display contains VS Code window.
Therefore, if VS Code is shown in external display, the dialog box is shown in other than that display, as you said.

In future version, I will make the extension support showing the dialog box on the position that is specified by moving the dialog box even if the position is in the external display.

**Comment by anseki** [comment]
I updated the extension. https://github.com/anseki/vscode-color/commit/c2559db427a21abc046a865516201146a52f8f7a
Only first time, please move the dialog box onto the position you desire.
