### ISSUE TITLE
ALT + C P, not working

### ISSUE THREAD

**Issue by robert-hoffmann** [anseki/vscode-color#22]
- Extension Version: 0.2.2
- VS Code Version: 1.8.1
- OS Version: win 10
- Node.js Version (result of command `node -v`):  6.9.1
- NPM Version (result of command `npm -v`): 4.0.2

Steps to Reproduce:

1.  Install
2.  ALT + C P

The extension works when invoking from the command palette, but it does not set up the necessary keyboard shortcut:
``The key combination (ALT + C, ALT + P) is not a command``

**Comment by robert-hoffmann** [comment]
My bad, it works..

You must hit ALT+C, then stop holding those keys, and afterwards hit P

-Robert

**Comment by anseki** [comment]
Hi @robert-hoffmann, thank you for the comment.
The "2 steps" keyboard shortcuts system like that is one of VS Code features. And also, many text editors and IDEs support that, it's popular UI.
But if you don't like that, you can change that keyboard shortcut easily.
http://code.visualstudio.com/docs/customization/keybindings

**Comment by robert-hoffmann** [comment]
Yes i'm used to visual studio ..so i was not expecting to let go of they keys.

But the extension works fine, and is quite nice.

Thanks !

**Comment by BobbyBabes** [comment]
@robert-hoffmann You are not alone. Ii also tripped me up. ;)
Glad that I found this issue.

**Comment by anseki** [comment]
Hi @BobbyBabes, thank you for the comment.

As I said, if you don't like IDE style shortcuts, you can change it easily.
http://code.visualstudio.com/docs/customization/keybindings

**Comment by DollarAkshay** [comment]
Was about to open an issue when I saw this 😅

**Comment by anseki** [comment]
Hi @DollarAkshay, thank you for the comment.
Sorry, my English is poor.
Do you mean that you had an issue about something, and that was solved?
Or, did you comment because you could not solve something?

**Comment by DollarAkshay** [comment]
Even I was trying Alt+C, Alt+P, I dint realize I had to remove my finger from the Alt key.

**Comment by anseki** [comment]
Those key-strokes are popular, and you can see those style in documents of VS Code and other IDEs.
So, did you already understand that, now?
That is, I don't know the reason that you commented that.

**Comment by BobbyBabes** [comment]
@anseki I didn't want to respond earlier in January (see above) to avoid a discussion.
I'm pretty sure that we all know about the **chord** key bindings.
I was not asking you to change anything. I know now how to interpret the way you documented chords.

What confused me is how `Alt+C P` is written. That's why I wrote _"tripped me up"_.
`Alt+C, P` or `Alt+C; P` would have left no doubt for me what to type.
It's similar to `Ctrl+K, W` `Ctrl+K, L` `Ctrl+K, P` `Ctrl+K, I` `Ctrl+E, F` `Ctrl+E, N` `Ctrl+E, X` etc as seen in the **Visual Studio** keybinding docs : https://msdn.microsoft.com/en-us/library/da5kh0wa.aspx
They even add a comma between sequences like `Ctrl+K, Ctrl+M` `Ctrl+K, Ctrl+N` `Ctrl+K, Ctrl+X` `Ctrl+K, Ctrl+P` etc. (Where I think it is not necessary at all.)

While **Visual Studio Code**'s key bindings do not add a comma to `Ctrl+K Ctrl+S` `Ctrl+K Ctrl+T`, etc. Which they do mention explicitly though :
> Chords (two separate keypress actions) are described by separating the two keypresses with a space. E.g.: ctrl+k ctrl+c.
**EDIT:** https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by anseki** [comment]
@BobbyBabes, thank you for the comment.
I agree. Some documents might often confuse us.
Anyway, I think that the current orthography `Alt + C P` is best for the time being because it should conform to the document of Visual Studio Code. Inconsistent documents confuse users more.

Also, I will add information or something about key-strokes to the document.
Thank you 😄
