### ISSUE TITLE
Color Palette customization

### ISSUE THREAD

**Issue by Fred-Vatin** [anseki/vscode-color#42]
- Extension Version: 0.4.1
- VS Code Version: 1.13.0
- OS Version: Win 10 (14393) x64

In documentation:

>  Also, you can specify color palettes that are loaded always, or color palettes that are loaded for only a project.

I don't see any settings to exclude some palettes. How to achieve that?

Can I set a environment variable in `colorHelper.storeDir` to point to the default VS Code user settings directory for instance? So I could create my own palettes that would be sync with my other user settings.

**Comment by anseki** [comment]
Hi @freMea, thank you for the comment.

You can specify a directory that contains color palettes via `colorHelper.storeDir`.
If you specified that in the User Settings, that is a directory that contains default color palettes.
If you specified that in the Workspace Settings, that is a directory that contains color palettes for the current project.

**Comment by Fred-Vatin** [comment]
@anseki 

I suggest, in _Color Palettes_ section in the home page documentation, you insert a direct link to :
https://github.com/anseki/vscode-color/blob/master/palettes/README.md

**Comment by anseki** [comment]
Thank you for the suggestion.
We should not insert that link because the document can be accessed locally.
The document is copied to a directory that specified via `colorHelper.storeDir`.
See: https://github.com/anseki/vscode-color#colorhelperstoredir

And also, please make new issue if you want to comment about another topic that is not your first question.
And please close this issue if it was solved.

**Comment by anseki** [comment]
Thank you 😄
