### ISSUE TITLE
Convert from named color doesn't work

### ISSUE THREAD

**Issue by MrLuje** [anseki/vscode-color#5]
Used "Convert color" from "Named"

![image](https://cloud.githubusercontent.com/assets/632075/16800877/ca7041ce-48f7-11e6-9d0c-5a5729326925.png)

![image](https://cloud.githubusercontent.com/assets/632075/16800843/a4ce2bac-48f7-11e6-8030-775c0e122ae5.png)

I'm using vscode 1.3.1

**Comment by anseki** [comment]
Hi @MrLuje, thank you for the report.

Could you tell me more information, please?
That looks like strange behavior because "Convert Color" command can not show the dialog box.
So, which color notation (e.g. "HWB", "RGB / RGBA", etc.,) did you choose from a list at top of VS Code window (not in the dialog box), after you executed "Convert Color" command?
And, when was that error message shown?

**Comment by anseki** [comment]
No reply came, and I close this issue.
