### ISSUE TITLE
"[processBridge]: Error: Unknown version of npm"

### ISSUE THREAD

**Issue by mklickman** [anseki/vscode-color#6]
When running the "pick color" command, after a short delay, I receive the afore-mentioned error message.

VS Code v1.4.0
OS X 10.11.6 (El Capitan)
Node v5.10.1
NPM v3.8.6

I am using NVM, which very well could be contributing to the issue. My integrated terminal works, including running `node -v` and `npm -v` (how I got the numbers above). Please let me know if you need me to clarify anything else. Thanks for all your hard work on this, can't wait to get it working!

**Comment by anseki** [comment]
Hi @mklickman, thank you for the report.

I think, your Node not might be enabled in a process VS Code is running.
If you use a Node version manager that doesn't support "default version", you must call nvm in a terminal before you start VS Code because the Node must be enabled in a process VS Code is running. And you must start VS Code in the same process.
If you use a Node version manager that supports default version (e.g. https://github.com/creationix/nvm), you can set default version by `nvm alias default node` to start VS Code without calling nvm.

**Comment by mklickman** [comment]
Thanks for responding! I do have a default version of node set, and just to be sure, I started a shell with node enabled, and then launched VS Code, but I was still met with the same error. Not sure what else I can try at this point.

**Comment by anseki** [comment]
When the error message was shown, more information might be shown in console.
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
If some information were shown, please let me know all of those.

**Comment by mklickman** [comment]
Here is a screenshot of my console output:

![image](https://cloud.githubusercontent.com/assets/354376/17686256/0a269c5e-6339-11e6-8e9c-769b963462b3.png)

**Comment by anseki** [comment]
The npm on your computer might have been installed into irregular path, or it might be broken.
Try these commands:

1.

```
node -e "console.log(require.resolve('npm'))"
```

A path to `npm.js` should be shown, e.g: `~/node/lib/node_modules/npm/lib/npm.js`.

2.

```
ls -al `node -e "var path=require('path');console.log(path.join(path.dirname(require.resolve('npm')),'utils'))"`
```

A list of files in `utils` directory should be shown.

3.

```
ls -al `node -e "console.log(require('path').dirname(require.resolve('npm')))"`
```

A list of files in npm's directory should be shown.

**Comment by anseki** [comment]
No reply came, and I close this issue.

**Comment by Gama11** [comment]
I was having the same issue, and got the following error executing the command you suggested:

```
C:\>node -e "console.log(require.resolve('npm'))"
module.js:327
    throw err;
    ^

Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at [eval]:1:21
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:409:26)
    at node.js:579:27
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

I didn't find any solution to it, so I asked about it on the #Node.js IRC channel:

```
<joepie91> Gama11: globally installed packages in Node are not meant to be used as libraries, only for command-line tools
<joepie91> anything you want to require() should always be installed locally
<Gama11> joepie91: ok.. that extension author is wrong then?
<joepie91> if they believe that it should be able to require a global `npm`, then yes, they are :)
<Gama11> joepie91: here's what he claimed: https://github.com/anseki/vscode-color/issues/6#issuecomment-240014922
<Gama11> joepie91: "A path to npm.js should be shown"
<joepie91> yeah, so that would be wrong, as far as I am aware
<joepie91> he's most likely basing this on his own environment where he might have things set up differently
```

Just an fyi, I know next to nothing about Node personally. :)

**Comment by anseki** [comment]
Hi @Gama11, thank you for the report.
So, that seems your mistake.
I indicated those commands for @mklickman because he showed the log that means the npm was found. The npm was already found in his computer regardless of whether it is installed globally or locally.
Therefore, both joepie91 and I are not wrong, you must [check the log](https://github.com/anseki/vscode-color/issues/6#issuecomment-239133249) first.
If some information were shown, please let me know all of those.

**Comment by Gama11** [comment]
Hm, this is interesting... I had already uninstalled the extension, so I now reinstalled it to test this - and it works just fine. I can't think of anything meaningful that changed between then and now.
Perhaps the key was to reinstall Node after all (one of the things I tried, I did have quite an old version I think...), but for some reason the plugin had the be reinstalled as well after that?

Anyway, thanks for your help!

**Comment by anseki** [comment]
I'm relieved at your report. :smiley: 
I think, the npm might have been not installed because Node.js is installed by various ways such as Version Manager.
Your case is different from @mklickman's case in that the npm could not be loaded. It is available now by re-installing Node.js.
I don't know  why loaded npm doesn't work because unfortunately @mklickman doesn't reply.
